import type { ChatMessage, ChatProvider } from "../providers/index.js";

export type IdentifiedMessage = ChatMessage & { id: number };

/** Same rough chars-per-token heuristic already used for token estimates
 *  elsewhere (devbuddy stats) when a provider doesn't report exact usage. */
export function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

function estimateMessagesTokens(messages: { content: string }[]): number {
  return messages.reduce((sum, m) => sum + estimateTokens(m.content), 0);
}

/** Resolves a configured compactThreshold ("off" or a number-as-string) into
 *  a token count, or null when auto-compaction is disabled. */
export function resolveCompactThreshold(configured: string): number | null {
  if (configured === "off") return null;
  const n = Number(configured);
  return Number.isFinite(n) && n > 0 ? n : null;
}

/**
 * Whether the current conversation is large enough to be worth compacting:
 * an estimated token count over the threshold, and enough messages that
 * there's actually something to summarize once the recent ones are kept.
 */
export function shouldCompact(
  messages: { role: ChatMessage["role"]; content: string }[],
  thresholdTokens: number | null,
  keepRecent: number
): boolean {
  if (thresholdTokens === null) return false;
  const nonSystem = messages.filter((m) => m.role !== "system");
  if (nonSystem.length <= keepRecent) return false;
  return estimateMessagesTokens(messages) > thresholdTokens;
}

export interface CompactionResult {
  /** The replacement conversation for continuing live: [system?, summary, ...keptVerbatim]. */
  messages: ChatMessage[];
  summaryMessage: ChatMessage;
  /** DB row id of the first kept-verbatim message - the caller persists this
   *  as the session's new compaction cutoff (see ProjectMemory.setCompactionPoint). */
  keepFromMessageId: number;
  compactedCount: number;
}

const SUMMARY_SYSTEM_PROMPT =
  "You summarize developer-agent conversations concisely and accurately, for continuing the same task later.";

const SUMMARY_REQUEST =
  "Summarize the conversation above into a concise but complete brief for continuing this task: " +
  "what was asked, what was done (files changed, commands run, decisions made), and what's still open. " +
  "Respond with ONLY the summary, no preamble.";

/**
 * Replaces the older portion of a conversation with one summary message
 * generated by the model itself, keeping the most recent `keepRecent`
 * non-system messages verbatim. `identified` must be a session's current,
 * id-tagged message window (ProjectMemory.getSessionMessagesWithIds) -
 * operating on real DB ids, rather than the caller's own in-memory copy,
 * is what makes it safe to compute exactly where the next compaction
 * should cut regardless of any earlier compaction.
 *
 * Returns null when there isn't enough to compact (see shouldCompact) -
 * callers should check that first for auto-compaction; this makes it safe
 * to call directly too (e.g. a manual "/compact"), it just no-ops.
 */
export async function compactMessages(
  provider: ChatProvider,
  model: string,
  identified: IdentifiedMessage[],
  keepRecent: number
): Promise<CompactionResult | null> {
  const systemMessage = identified.find((m) => m.role === "system");
  const rest = identified.filter((m) => m.role !== "system");
  if (rest.length <= keepRecent) return null;

  const toSummarize = rest.slice(0, rest.length - keepRecent);
  const toKeep = rest.slice(rest.length - keepRecent);

  const summaryRequest: ChatMessage[] = [
    { role: "system", content: SUMMARY_SYSTEM_PROMPT },
    ...toSummarize.map(({ role, content }) => ({ role, content })),
    { role: "user", content: SUMMARY_REQUEST },
  ];

  const result = await provider.streamChat({ model, messages: summaryRequest });
  const summaryMessage: ChatMessage = {
    role: "assistant",
    content: `[Earlier conversation summary]\n${result.content}`,
  };

  const keptPlain = toKeep.map(({ role, content }) => ({ role, content }));
  return {
    messages: systemMessage ? [{ role: systemMessage.role, content: systemMessage.content }, summaryMessage, ...keptPlain] : [summaryMessage, ...keptPlain],
    summaryMessage,
    keepFromMessageId: toKeep[0].id,
    compactedCount: toSummarize.length,
  };
}
